#!/usr/bin/env python3
"""
One-shot migration: create the Neon Postgres schema, copy data from the
local SQLite DB (kept untouched as fallback), and create the two roles:

  crawler_rw  read-write  — used by the local pipeline
  admin_ro    read-only   — used by the deployed admin panel

Requires DATABASE_URL (Neon owner connection string) in .env.
Role passwords come from CRAWLER_DB_PASSWORD / ADMIN_DB_PASSWORD, or are
generated and printed once — store them immediately.

Idempotent: safe to re-run. Existing rows are matched by url and skipped;
existing roles keep their password unless the env var is set.

  python scripts/migrate_to_neon.py            # schema + roles + copy
  python scripts/migrate_to_neon.py --schema-only
"""
import os
import secrets
import sqlite3
import sys
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).parent))
from db import connect  # noqa: E402

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

SQLITE_PATH = Path("data/crawler.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS sites (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url             TEXT UNIQUE NOT NULL,
  source          TEXT NOT NULL DEFAULT 'unknown',
  status          TEXT NOT NULL DEFAULT 'pending',
  screenshot_path TEXT,
  screenshot_key  TEXT,          -- R2 object key (upload step; binaries never in PG)
  error           TEXT,
  created_at      BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM now())::BIGINT,
  crawled_at      BIGINT,
  analyzed_at     BIGINT,
  ai_score        REAL,          -- Vision score 1-10  (was design_score in SQLite)
  local_score     REAL,          -- deterministic heuristics 0-10, never merged with ai_score
  dom_nodes       INTEGER,       -- captured at crawl time, feeds local_score
  category        TEXT,
  ai_feedback     TEXT,
  title           TEXT,
  notified_at     BIGINT
);
CREATE INDEX IF NOT EXISTS idx_sites_status   ON sites(status);
CREATE INDEX IF NOT EXISTS idx_sites_source   ON sites(source);
CREATE INDEX IF NOT EXISTS idx_sites_ai_score ON sites(ai_score);
CREATE INDEX IF NOT EXISTS idx_sites_crawled  ON sites(crawled_at);

-- Drop the retired provenance column if a previous schema created it
ALTER TABLE sites DROP COLUMN IF EXISTS score_origin;
"""


def ensure_role(conn, role: str, password: str, created: dict) -> None:
    exists = conn.execute(
        "SELECT 1 FROM pg_roles WHERE rolname = %s", (role,)
    ).fetchone()
    if exists:
        print(f"  role {role}: already exists (password unchanged)")
        if os.getenv(f"{role.upper().replace('_RW','').replace('_RO','')}_DB_PASSWORD"):
            pass  # explicit passwords are only applied at creation — change via console if needed
        return
    # role names are fixed constants; password is quoted via literal escaping
    conn.execute(
        f"CREATE ROLE {role} LOGIN PASSWORD '{password.replace(chr(39), chr(39)*2)}'"
    )
    created[role] = password
    print(f"  role {role}: created")


def apply_grants(conn) -> None:
    grants = [
        "GRANT USAGE ON SCHEMA public TO crawler_rw",
        "GRANT SELECT, INSERT, UPDATE, DELETE ON sites TO crawler_rw",
        "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO crawler_rw",
        "GRANT USAGE ON SCHEMA public TO admin_ro",
        "GRANT SELECT ON sites TO admin_ro",
    ]
    for g in grants:
        conn.execute(g)
    print("  grants applied (crawler_rw: rw on sites; admin_ro: select only)")


def copy_sqlite(conn) -> None:
    if not SQLITE_PATH.exists():
        print(f"  no {SQLITE_PATH} — nothing to copy (fresh install)")
        return

    lite = sqlite3.connect(SQLITE_PATH)
    rows = lite.execute(
        "SELECT id, url, source, status, screenshot_path, error, created_at, "
        "crawled_at, analyzed_at, design_score, category, ai_feedback, title, notified_at "
        "FROM sites ORDER BY id"
    ).fetchall()
    lite.close()

    if not rows:
        print("  local SQLite is empty — nothing to copy")
        return

    with conn.cursor() as cur:
        cur.executemany(
            """INSERT INTO sites
                 (id, url, source, status, screenshot_path, error, created_at,
                  crawled_at, analyzed_at, ai_score, category, ai_feedback, title, notified_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
               ON CONFLICT (url) DO NOTHING""",
            rows,
        )
    # keep the identity sequence ahead of copied ids
    conn.execute(
        "SELECT setval(pg_get_serial_sequence('sites','id'), "
        "(SELECT COALESCE(MAX(id),0)+1 FROM sites), false)"
    )
    n = conn.execute("SELECT COUNT(*) FROM sites").fetchone()[0]
    print(f"  copied {len(rows)} SQLite rows → Postgres now has {n} rows "
          f"(design_score → ai_score; local SQLite left untouched as fallback)")


def conn_string_for(role: str, password: str) -> str:
    """Derive a role-specific connection string from DATABASE_URL."""
    owner = os.environ["DATABASE_URL"]
    p = urlparse(owner)
    host = p.hostname or ""
    port = f":{p.port}" if p.port else ""
    db = p.path.lstrip("/") or "neondb"
    query = f"?{p.query}" if p.query else "?sslmode=require"
    return f"postgresql://{role}:{password}@{host}{port}/{db}{query}"


def main() -> None:
    schema_only = "--schema-only" in sys.argv

    conn = connect(role="owner", autocommit=True)
    print(f"Connected to {urlparse(os.environ['DATABASE_URL']).hostname}")

    print("\n[1/3] schema")
    conn.execute(SCHEMA)
    print("  sites table + indexes ensured")

    print("\n[2/3] roles")
    created: dict = {}
    crawler_pw = os.getenv("CRAWLER_DB_PASSWORD") or secrets.token_urlsafe(24)
    admin_pw = os.getenv("ADMIN_DB_PASSWORD") or secrets.token_urlsafe(24)
    ensure_role(conn, "crawler_rw", crawler_pw, created)
    ensure_role(conn, "admin_ro", admin_pw, created)
    apply_grants(conn)

    if not schema_only:
        print("\n[3/3] data copy")
        copy_sqlite(conn)
    else:
        print("\n[3/3] data copy skipped (--schema-only)")

    conn.close()

    if created:
        print("\n── connection strings (store these NOW — passwords are not saved) ──")
        for role, pw in created.items():
            var = "CRAWLER_DATABASE_URL" if role == "crawler_rw" else "ADMIN_DATABASE_URL"
            print(f"\n{var}={conn_string_for(role, pw)}")
    print("\nDone. Put CRAWLER_DATABASE_URL / ADMIN_DATABASE_URL into .env, then:")
    print("  node crawler/stats.js        # verify pipeline connectivity")
    print("  python scripts/analyze.py --export-only   # verify python side")


if __name__ == "__main__":
    main()
